version: '3'
services:
   app:
      build:
         context: .
      ports:
         - "8090:8090"
      depends_on:
         - mongo
   mongo:
      image: mongo
      ports:
         - "27017:27017"